Feature/new update management
qbeyond/terraform-azurerm-update-management pull request #5
Opened 2023-10-16 09:17 UTC by QBY-ChristianHartmann

# Description

For MALZ we developed a new update management. This includes a new syntax for the severity group tags and an automation runbook that creates + updates the update deployment groups.

# Change overview (tick true):

- [x] This introduces backward incompatible changes
- [ ] This adds a new backward compatible Feature
- [ ] This fixes a Bug

# Version information: 

- Previous Version: `1.0.1`

- Next Version based on [Semantic Versioning](https://semver.org/#summary) (see above): `1.0.0`

# How Has This Been Tested?

- [x] Apply of all examples was successful

# Checklist:

- [x] I have run tests and documented them above
- [x] I have performed a self-review of my own code
- [x] I have updated the documentation
- [x] I have updated the CHANGELOG

2023-10-16 11:02 UTC, QBY-ThimoLimpert requested changes
The next version can't be 1.0.0 if the previous version was 1.0.1. I suppose it should be 2.0.0

2023-10-16 11:02 UTC, ghost commented on main.tf
> +  name                    = "Every 12 Hours 7AM"
How can i run a schedule every 12 hours at 7 AM? That's 24 hours

2023-10-16 11:02 UTC, ghost commented on main.tf
> +resource "time_static" "tomorrow_7am" {
```suggestion
resource "time_static" "schedule_start_tomorrow_7am" {
# The start_time of schedule needs to be in the future
# Use time static to avoid recreating schedule on any invocation
```
Make the intend of the resource clear

2023-10-16 11:02 UTC, ghost commented on main.tf
> +  automation_account_name = var.automation_account.name
```suggestion
  resource_group_name     = time_static.tomorrow_7am.automation_account.resource_group_name
  automation_account_name = time_static.tomorrow_7am.automation_account.name
```

as changing rg or automation account name requires a recreation, the time_static should also be recreated.

2023-10-16 11:02 UTC, ghost commented on runbooks/Set-DeploymentSchedules.ps1
> +| project subscriptionId
Avoid iterating though subscriptions multiple times. (once by cloud, once local)
```suggestion
| project subscriptionId=strcat("/subscriptions/",subscriptionId)
```

2023-10-16 11:02 UTC, ghost commented on runbooks/Set-DeploymentSchedules.ps1
> +|  project ['tags'].["Severity Group Monthly"]
```suggestion
|  project ['tags'].["Severity Group Monthly"]
| distinct ['tags'].["Severity Group Monthly"]
```
reduce transferred data and avoid another loop locally by requesting only distinct severity groups

2023-10-16 11:05 UTC, QBY-ChristianHartmann commented on main.tf
> +  name                    = "Every 12 Hours 7AM"
every 12 hours starting 7AM, i rename

2023-10-17 10:43 UTC, QBY-ThimoLimpert commented on CHANGELOG.md
> +[2.0.0] - 2023-10-17
```suggestion
## [2.0.0] - 2023-10-17

Complete rewrite of the module. It now deploys a runbook to dynamically create the required update schedules based on the used tags. Furthermore it uses the new severity group structure. 

To use the new version, remove all previous module calls and create **only one** call of the new module. Furthermore upgrade all tags from the old severity group structure to the new one. You can monitor the usage of wrong text in the output of the runbook.
```

2023-10-17 10:45 UTC, QBY-ThimoLimpert approved these changes

2023-10-17 10:46 UTC, merged